server:
  port: 8082

spring:
  application:
    name: msa4-lms-v2-academic
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:lms_academic}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  jackson:
    deserialization:
      fail-on-unknown-properties: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

security:
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    com.msa4lmsv2academic: debug
